In [1]:
# 필요한 라이브러리 import
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 붓꽃 데이터 로드
iris = load_iris()
X = iris.data  # 특징 (꽃받침, 꽃잎 길이, 너비 등)
y = iris.target  # 라벨 (품종)

# 데이터셋을 학습용과 테스트용으로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 특성 scaling (SVM, Logistic Regression 성능 향상에 도움이 됨)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 1. 랜덤 포레스트(Random Forest) 분류
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Random Forest Accuracy: ", accuracy_score(y_test, rf_pred))
print("Random Forest Confusion Matrix: \n", confusion_matrix(y_test, rf_pred))
print("Random Forest Classification Report: \n", classification_report(y_test, rf_pred))

# 2. 결정 트리(Decision Tree) 분류
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
print("\nDecision Tree Accuracy: ", accuracy_score(y_test, dt_pred))
print("Decision Tree Confusion Matrix: \n", confusion_matrix(y_test, dt_pred))
print("Decision Tree Classification Report: \n", classification_report(y_test, dt_pred))

# 3. 서포트 벡터 머신(SVM) 분류
svm_model = SVC(kernel='linear', random_state=42)  # linear kernel 사용
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
print("\nSVM Accuracy: ", accuracy_score(y_test, svm_pred))
print("SVM Confusion Matrix: \n", confusion_matrix(y_test, svm_pred))
print("SVM Classification Report: \n", classification_report(y_test, svm_pred))

# 4. 로지스틱 회귀(Logistic Regression) 분류
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
print("\nLogistic Regression Accuracy: ", accuracy_score(y_test, lr_pred))
print("Logistic Regression Confusion Matrix: \n", confusion_matrix(y_test, lr_pred))
print("Logistic Regression Classification Report: \n", classification_report(y_test, lr_pred))


Random Forest Accuracy:  1.0
Random Forest Confusion Matrix: 
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Random Forest Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Decision Tree Accuracy:  1.0
Decision Tree Confusion Matrix: 
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Decision Tree Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg  

In [1]:
import pandas as pd

# 붓꽃 데이터 CSV 파일 읽기
file_path = "C:/Users/ghom9/iris.csv"  # 본인이 iris.csv를 저장한 경로를 입력합니다.
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()
df.columns()

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ghom9/iris.csv'

In [1]:
import pandas as pd

# 붓꽃 데이터 CSV 파일 읽기
file_path = "C:/다운로드/iris.csv"  # 본인이 iris.csv를 저장한 경로를 입력합니다.
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()
df.columns()

FileNotFoundError: [Errno 2] No such file or directory: 'C:/다운로드/iris.csv'

In [2]:
#\Users\ghom9

import pandas as pd

# 붓꽃 데이터 CSV 파일 읽기
file_path = "C:\Users\ghom9/iris.csv"  # 본인이 iris.csv를 저장한 경로를 입력합니다.
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()
df.columns()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2445025868.py, line 6)

In [3]:
import pandas as pd

# 붓꽃 데이터 CSV 파일 읽기
file_path = "C:/Users/ghom9/iris.csv"  # 본인이 iris.csv를 저장한 경로를 입력합니다.
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()
df.columns()

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ghom9/iris.csv'

In [4]:
import pandas as pd

# 붓꽃 데이터 CSV 파일 읽기
file_path = "C:/Users/ghom9/Downloads/iris.csv" # 본인이 iris.csv를 저장한 경로를 입력합니다.
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()
df.columns()

TypeError: 'Index' object is not callable

In [5]:
import pandas as pd

# 붓꽃 데이터 CSV 파일 읽기
file_path = "C:/Users/ghom9/Downloads/iris.csv" # 본인이 iris.csv를 저장한 경로를 입력합니다.
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()
df.columns

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')

In [6]:
# 1. 랜덤 포레스트(Random Forest) 분류
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Random Forest Accuracy: ", accuracy_score(y_test, rf_pred))
print("Random Forest Confusion Matrix: \n", confusion_matrix(y_test, rf_pred))
print("Random Forest Classification Report: \n", classification_report(y_test, rf_pred))

# 2. 결정 트리(Decision Tree) 분류
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
print("\nDecision Tree Accuracy: ", accuracy_score(y_test, dt_pred))
print("Decision Tree Confusion Matrix: \n", confusion_matrix(y_test, dt_pred))
print("Decision Tree Classification Report: \n", classification_report(y_test, dt_pred))

# 3. 서포트 벡터 머신(SVM) 분류
svm_model = SVC(kernel='linear', random_state=42)  # linear kernel 사용
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
print("\nSVM Accuracy: ", accuracy_score(y_test, svm_pred))
print("SVM Confusion Matrix: \n", confusion_matrix(y_test, svm_pred))
print("SVM Classification Report: \n", classification_report(y_test, svm_pred))

# 4. 로지스틱 회귀(Logistic Regression) 분류
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
print("\nLogistic Regression Accuracy: ", accuracy_score(y_test, lr_pred))
print("Logistic Regression Confusion Matrix: \n", confusion_matrix(y_test, lr_pred))
print("Logistic Regression Classification Report: \n", classification_report(y_test, lr_pred))

NameError: name 'RandomForestClassifier' is not defined

In [7]:
# 필요한 라이브러리 import
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 붓꽃 데이터 로드
iris = load_iris()
X = iris.data  # 특징 (꽃받침, 꽃잎 길이, 너비 등)
y = iris.target  # 라벨 (품종)

# 데이터셋을 학습용과 테스트용으로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 특성 scaling (SVM, Logistic Regression 성능 향상에 도움이 됨)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 1. 랜덤 포레스트(Random Forest) 분류
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print("Random Forest Accuracy: ", accuracy_score(y_test, rf_pred))
print("Random Forest Confusion Matrix: \n", confusion_matrix(y_test, rf_pred))
print("Random Forest Classification Report: \n", classification_report(y_test, rf_pred))

# 2. 결정 트리(Decision Tree) 분류
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
print("\nDecision Tree Accuracy: ", accuracy_score(y_test, dt_pred))
print("Decision Tree Confusion Matrix: \n", confusion_matrix(y_test, dt_pred))
print("Decision Tree Classification Report: \n", classification_report(y_test, dt_pred))

# 3. 서포트 벡터 머신(SVM) 분류
svm_model = SVC(kernel='linear', random_state=42)  # linear kernel 사용
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
print("\nSVM Accuracy: ", accuracy_score(y_test, svm_pred))
print("SVM Confusion Matrix: \n", confusion_matrix(y_test, svm_pred))
print("SVM Classification Report: \n", classification_report(y_test, svm_pred))

# 4. 로지스틱 회귀(Logistic Regression) 분류
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
print("\nLogistic Regression Accuracy: ", accuracy_score(y_test, lr_pred))
print("Logistic Regression Confusion Matrix: \n", confusion_matrix(y_test, lr_pred))
print("Logistic Regression Classification Report: \n", classification_report(y_test, lr_pred))


Random Forest Accuracy:  1.0
Random Forest Confusion Matrix: 
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Random Forest Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Decision Tree Accuracy:  1.0
Decision Tree Confusion Matrix: 
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Decision Tree Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg  